# Site settings
title: Jiang's Blog
email: rwangzj@live.com
description: One thorn of experience is worth a whole wilderness of warning.
baseurl: ""
url: https://wangzj.github.io
twitter_username: nil
github_username: wangzj
# owner:
#   disqus_shortname: fixedpoint

valine:
  enable: true
  appid: 0WjzvHTbFLYI4eAKrgbWTlf0-gzGzoHsz
  appkey: 8jNNbjVSa2w4jM9KtN4CejbT
  # verify: true # 验证码
  # notify: true # 评论回复邮箱提醒
  # avatar: mp # 匿名者头像选项
  placeholder: Just go go!

# Build settings
markdown: kramdown
highlighter: pygments
paginate: 10
excerpt_separator: "<!--more-->"

gems: [jekyll-paginate]

exclude: ["README.md"]
